kind = "web"
previewPath = "/"
title = "KEROPROMO"
version = "1.0.0"
id = "artifacts/keropromo"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
localPort = 24846
name = "web"
paths = ["/"]

[services.development]
run = "pnpm --filter @workspace/keropromo run dev"

[services.env]
PORT = "24846"
BASE_PATH = "/"

[services.production]
build = ["pnpm", "--filter", "@workspace/keropromo", "run", "build"]
publicDir = "artifacts/keropromo/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"
